# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueN6_SxCj4IcyVrZI_ldT_8X-KK5C6Xk
"""

!pip install --upgrade openai

import openai
import os
import time

# ... (rest of your code) ...

def query_messi_info(query):
    max_retries = 3  # Maximum number of retries
    retry_delay = 1  # Initial retry delay in seconds

    for i in range(max_retries):
        try:
            response = openai.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": f"Given the following information about Lionel Messi: {messi_info}"},
                    {"role": "user", "content": query},
                ],
                max_tokens=150
            )
            return response.choices[0].message.content.strip()
        except openai.RateLimitError: # Changed from openai.error.RateLimitError to openai.RateLimitError
            if i < max_retries - 1:  # Don't sleep on the last retry
                time.sleep(retry_delay)
                retry_delay *= 2  # Increase the delay exponentially
                print(f"Rate limit hit. Retrying in {retry_delay} seconds...")
            else:
                raise  # Re-raise the exception if all retries fail

user_query = "What are Lionel Messi's major achievements?"
answer = query_messi_info(user_query)

print(answer)